import { PracticeArea, CasPrecedent, Testimonial, TeamMember, FeeStructureItem, NewsletterArticle } from "./types";

/* ── Practice Areas ── */
export const PRACTICE_AREAS: PracticeArea[] = [
  {
    id: "sports-law",
    title: "Sports Law - CAS & ETH-ADA",
    description: "Premier sports law practice with proven experience at the Court of Arbitration for Sport (CAS) and ETH-ADA. We handle anti-doping violations, eligibility disputes, contract negotiations, and disciplinary proceedings for athletes, federations, and clubs.",
    icon: "Trophy",
    highlights: [
      "CAS anti-doping defense & appeals",
      "ETH-ADA litigation & sanction reductions",
      "Eligibility & team selection disputes",
      "Athlete contract negotiation & dispute resolution",
      "WADA code compliance & advisory",
    ],
    gradient: "from-emerald-500/20 via-transparent to-transparent",
    details: [],
  },
  {
    id: "banking-insurance",
    title: "Banking & Insurance",
    description: "Comprehensive legal services for financial institutions, insurers, and policyholders. We advise on regulatory compliance, claims disputes, policy interpretation, and risk management across the Ethiopian banking and insurance sectors.",
    icon: "Bank",
    highlights: [
      "Regulatory compliance & licensing",
      "Insurance claims disputes & litigation",
      "Banking & finance transactions",
      "Risk assessment & policy drafting",
      "Debt recovery & enforcement",
    ],
    gradient: "from-emerald-500/20 via-transparent to-transparent",
    details: [],
  },
  {
    id: "investment",
    title: "Investment Practice",
    description: "Strategic legal counsel for domestic and foreign investors navigating Ethiopia's evolving investment landscape. We handle joint ventures, FDI structuring, shareholder agreements, and investment dispute resolution.",
    icon: "CurrencyDollar",
    highlights: [
      "Foreign direct investment (FDI) structuring",
      "Joint venture & shareholder agreements",
      "Investment dispute resolution",
      "Regulatory approvals & licensing",
      "Cross-border transactions",
    ],
    gradient: "from-amber-500/20 via-transparent to-transparent",
    details: [],
  },
  {
    id: "employment",
    title: "Employment Law",
    description: "Full-service employment law representation for employers and employees. We advise on labor contracts, termination disputes, workplace policies, and compliance with Ethiopian labor law and international standards.",
    icon: "Handshake",
    highlights: [
      "Employment contract drafting & review",
      "Unfair dismissal & termination disputes",
      "Workplace policy & compliance",
      "Collective bargaining & labor relations",
      "Employment tribunal representation",
    ],
    gradient: "from-emerald-500/20 via-transparent to-transparent",
    details: [],
  },
  {
    id: "contract",
    title: "Contract Law",
    description: "Expert contract law services covering drafting, negotiation, review, and dispute resolution. We ensure your agreements are robust, enforceable, and aligned with your commercial objectives under Ethiopian and international law.",
    icon: "Notepad",
    highlights: [
      "Commercial contract drafting & review",
      "Breach of contract litigation",
      "Contract negotiation & advisory",
      "International contract law",
      "Specific performance & damages claims",
    ],
    gradient: "from-amber-500/20 via-transparent to-transparent",
    details: [],
  },
  {
    id: "construction",
    title: "Construction Law",
    description: "Specialized legal services for the construction industry, including contract formation, dispute resolution, regulatory compliance, and project risk management for developers, contractors, and suppliers.",
    icon: "Buildings",
    highlights: [
      "Construction contract drafting & review",
      "Dispute resolution & adjudication",
      "Regulatory compliance & permits",
      "Project risk management",
      "Employer & contractor representation",
    ],
    gradient: "from-emerald-500/20 via-transparent to-transparent",
    details: [],
  },
];

/* ── CAS Precedents ── */
export const CAS_PRECEDENTS: CasPrecedent[] = [
  { year: "2025", title: "Diribe Welteji v. International Federation", outcome: "Full clearance — athlete competed & won internationally (CAS landmark)", category: "Procedural Victory", chargeType: "Refusal to Submit Sample", link: "https://www.instagram.com/p/DGode5yNIVR/" },
  { year: "2023", title: "Gaddisa Tajebe v. ETH-ADA", outcome: "6-year ban reduced to 2 years on appeal — landmark sanction reduction", category: "Appeal Victory", chargeType: "First Charge of Doping" },
  { year: "2024", title: "Samuel Abate v. ETH-ADA", outcome: "Ineligibility period substantially reduced — successful mitigation", category: "Appeal Victory" },
  { year: "2025", title: "Adeladelew Mamo v. National Federation", outcome: "Penalty significantly reduced on appeal — procedural victory", category: "Procedural Victory" },
  { year: "2022", title: "Eligibility Appeal for Olympic Athlete", outcome: "Eligibility reinstated 30 days before Games — expedited ruling", category: "Eligibility" },
  { year: "2021", title: "International Transfer Fee Arbitration", outcome: "FIFA DRC ruling in favor of client — fee confirmed", category: "Transfers" },
];

/* ── Team Members ── */
export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "yigermal-melkam",
    name: "Yigermal Melkam",
    title: "Founder & Lead Counsel",
    bio: "Founder of YMA Law Office with extensive experience in international sports law, CAS arbitration, and corporate litigation. Successfully represented athletes before the Court of Arbitration for Sport (CAS) and ETH-ADA, securing landmark victories including full clearances and significant sanction reductions.",
    imageUrl: "https://lh3.googleusercontent.com/d/1dnDwrgDvM0QzMR0MzvSEqNssuqwC7d5m",
    specialties: ["Sports Law", "CAS Arbitration", "Anti-Doping Defense", "Corporate Litigation"],
  },
];

/* ── Testimonials ── */
export const TESTIMONIALS: Testimonial[] = [
  {
    id: "diribe-welteji",
    name: "Diribe Welteji",
    sport: "Middle-Distance Running (800m / 1500m)",
    nationality: "Ethiopia",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop&crop=face",
    quote: "Yigermal is the hardest working lawyer I have ever met. His deep understanding of sports law and his unwavering dedication carried me through the darkest time of my career. He treated me with dignity, fought with everything he had, and never stopped believing in me. I owe my future to him.",
    caseType: "CAS Arbitration",
    outcome: "Full Clearance (CAS)",
    year: "2025",
    headline: "A Fighter Who Never Backs Down",
    role: "Olympian and World Championship Medalist",
    highlights: [
      "Full clearance — no sanction imposed",
      "Provisional suspension lifted immediately after CAS hearing",
      "Continued international career with victories in China & Jamaica",
      "Landmark CAS defense — refusal to submit sample charge",
    ],
    fullStory: "Diribe Welteji, an Ethiopian Olympian and World Championship medalist, faced a career-threatening adverse finding under a refusal to submit sample charge. Lawyer Yigermal Melkam mounted an aggressive, multi-pronged defense before the Court of Arbitration for Sport (CAS), challenging the testing protocol, chain of custody, and sanction proportionality. The CAS panel delivered a decisive outcome: no penalty, zero sanction. Diribe's provisional suspension was lifted, and she returned to competition immediately — going on to win races in China, Jamaica, and on the global stage. This landmark victory reaffirmed YMA Law Office's reputation as one of the most effective athlete advocacy firms in international sport.",
    category: "CAS Arbitration",
  },
  {
    id: "gadisa-tajebe",
    name: "Gaddisa Tajebe",
    sport: "Distance Running (Marathon / Half-Marathon)",
    nationality: "Ethiopia",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=400&fit=crop&crop=face",
    quote: "When my career was hanging by a thread, Yigermal stepped in and built a strategy that gave me a fighting chance. His sharp mind, tireless work ethic, and deep knowledge of sports law turned my situation around. He didn't just win arguments — he won my freedom to compete again. I am forever indebted.",
    caseType: "ETHIO NADO Appeal",
    outcome: "6-Year Ban Reduced to 2 Years on Appeal",
    year: "2023",
    headline: "The Architect of My Comeback",
    role: "Marathon Medalist",
    highlights: [
      "6-year ban reduced to 2 years on appeal",
      "Challenged proportionality framework",
      "Secured athlete's right to resume international competition",
      "Established precedent for sanction reduction",
    ],
    fullStory: "Gaddisa Tajebe, an accomplished Ethiopian distance runner competing in marathons and half-marathons, faced a career-threatening 6-year ban that would have ended his athletic career. Lawyer Yigermal Melkam took the case before the relevant authorities, arguing that the sanction was disproportionate under the applicable rules and that critical mitigating factors had been overlooked. The panel agreed, substantially reducing the ban to 2 years. This decision allowed Gaddisa to resume his career and plan a comeback in international marathon competition.",
    category: "ETH-ADA Appeals",
  },
  {
    id: "samuel-abate",
    name: "Samuel Abate",
    sport: "Track & Field",
    nationality: "Ethiopia",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=400&fit=crop&crop=face",
    quote: "In my darkest hours, Yigermal was my rock. He didn't treat me like a case number — he treated me like family. He answered every call, calmed every fear, and fought with passion and precision. His compassion and brilliance made all the difference. I couldn't have survived without him.",
    caseType: "Sanction Reduction",
    outcome: "Ineligibility Period Substantially Reduced",
    year: "2024",
    headline: "A Lawyer Who Truly Cares",
    role: "Track & Field Athlete",
    highlights: [
      "Ineligibility period substantially reduced",
      "Demonstrated significant mitigating factors",
      "Proved no significant fault or negligence",
      "Allowed athlete to return to competition quickly",
    ],
    fullStory: "Samuel Abate, an Ethiopian track and field athlete, was handed a severe ineligibility period that threatened to end his athletic career. Lawyer Yigermal Melkam took the case and successfully argued that the athlete bore no significant fault or negligence, presenting evidence of mitigating circumstances that the initial hearing had not adequately considered. The appeal panel substantially reduced the ineligibility period, allowing Samuel to return to competition and continue his athletic pursuits.",
    category: "Sanction Reductions",
  },
  {
    id: "adeladelew-mamo",
    name: "Adeladelew Mamo",
    sport: "Marathon and Long Distance",
    nationality: "Ethiopia",
    imageUrl: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=400&fit=crop&crop=face",
    quote: "Yigermal's brilliance and dedication changed everything for me. He never stopped fighting, even when the odds were stacked against us. He believed in me when I had lost all faith. I am in the sport I love because of him.",
    caseType: "Procedural Appeal",
    outcome: "Penalty Substantially Reduced on Appeal",
    year: "2023",
    headline: "The Reason I Still Compete",
    role: "Marathon and Long Distance Athlete",
    highlights: [
      "Significant reduction of penalty on appeal",
      "Challenged procedural fairness",
      "Established mitigating circumstances on appeal",
      "Preserved athlete's eligibility for future competition",
    ],
    fullStory: "Adeladelew Mamo, an Ethiopian marathon and long distance athlete, faced a significant penalty following a procedural dispute. Lawyer Yigermal Melkam took on the appeal, arguing that the circumstances warranted significant mitigation. The appeal panel recognized the procedural concerns and substantially reduced the penalty, allowing Adeladelew to maintain his career in athletics. This case highlights Yigermal Melkam and Advocates Law Office's commitment to ensuring procedural fairness for all athletes.",
    category: "Procedural Appeals",
  },
  {
    id: "esikender-assefa",
    name: "Esikender Assefa",
    sport: "Real Estate Development",
    nationality: "Ethiopia",
    imageUrl: "",
    quote: "We have had the privilege of working with Mr. Yigermal as our legal counsel for several years. His professionalism, deep understanding of Ethiopian real estate law, and commitment to protecting our interests have been invaluable to our business operations.",
    caseType: "Real Estate & Corporate Law",
    outcome: "Ongoing Legal Counsel & Risk Management",
    year: "2024",
    headline: "Invaluable Legal Protection for Real Estate",
    role: "Managing Director, Abissinia Real Estate",
    highlights: [
      "Multi-year trusted legal counsel for Ethiopian real estate operations",
      "Deep expertise in Ethiopian real estate regulation and property law",
      "Strategic risk management and proactive interest protection",
      "Commercial contract drafting, negotiation, and dispute prevention",
    ],
    fullStory: "Abissinia Real Estate, a prominent real estate development and property management firm in Ethiopia, has partnered with Lawyer Yigermal Melkam as dedicated corporate legal counsel for several years. Lawyer Yigermal provides end-to-end legal support across property acquisitions, regulatory compliance, construction contracts, and commercial risk mitigation, safeguarding the firm's major assets and operational investments.",
    category: "Real Estate & Corporate",
  },
];

export const TESTIMONIAL_CATEGORIES = [
  { id: "all", label: "All Cases" },
  { id: "CAS Arbitration", label: "CAS Arbitration" },
  { id: "ETH-ADA Appeals", label: "ETH-ADA Appeals" },
  { id: "Procedural Appeals", label: "Procedural Appeals" },
  { id: "Sanction Reductions", label: "Sanction Reductions" },
  { id: "Real Estate & Corporate", label: "Real Estate & Corporate" },
];

/* ── Fee Structure ── */
export const FEE_STRUCTURE: FeeStructureItem[] = [
  {
    id: "hourly",
    title: "Hourly Billing",
    description: "Standard hourly rate for ongoing legal advisory, document review, and case management. Transparent time tracking with detailed billing statements.",
    price: "Contact for Rates",
    features: [
      "Transparent hourly billing",
      "Detailed time records",
      "No hidden fees",
      "Flexible engagement terms",
      "Senior counsel allocation",
    ],
  },
  {
    id: "fixed-consultation",
    title: "Fixed Consultation",
    description: "One-time legal consultation for specific legal questions, case assessment, or strategic advice. Ideal for initial case evaluation and legal opinion.",
    price: "From $200",
    popular: true,
    features: [
      "One-hour consultation session",
      "Case assessment & strategy",
      "Written legal opinion",
      "Next-steps action plan",
      "Follow-up email support",
    ],
  },
  {
    id: "retainer",
    title: "Monthly Retainer",
    description: "Ongoing legal support for corporations, sports federations, and organizations requiring continuous legal counsel and compliance monitoring.",
    price: "Custom Quote",
    features: [
      "Priority response time",
      "Unlimited consultations",
      "Contract review (up to 10/month)",
      "Compliance monitoring",
      "Dedicated counsel access",
    ],
  },
  {
    id: "anti-doping",
    title: "Anti-Doping Defense Package",
    description: "Specialized defense package for athletes facing anti-doping charges before ETHIO NADO, WADA, and CAS. Comprehensive representation from initial charge through final appeal.",
    price: "Custom Quote",
    features: [
      "Full CAS representation",
      "Evidence review & expert engagement",
      "Hearing preparation & advocacy",
      "Appeal strategy & filing",
      "Post-hearing follow-up",
    ],
  },
];

/* ── Newsletter Articles ── */
export const NEWSLETTER_ARTICLES: NewsletterArticle[] = [
  {
    id: "nl-1",
    title: "CAS Anti-Doping Update: New WADA Code Changes for 2025",
    excerpt: "Key changes to the World Anti-Doping Code that every Ethiopian athlete needs to know, including revised sanctioning guidelines and new procedural requirements.",
    date: "Jan 2025",
    category: "Regulatory Update",
    content: "The World Anti-Doping Agency (WADA) has introduced significant amendments to the World Anti-Doping Code, effective 2025. These changes include revised sanctioning guidelines, expanded definitions of prohibited methods, and new procedural requirements for sample collection. Ethiopian athletes and federations must be aware of these developments to ensure compliance and protect their rights.",
    author: "Yigermal Melkam",
    readTime: "4 min read",
  },
  {
    id: "nl-2",
    title: "Year in Review: Landmark Sports Law Cases in Ethiopia 2024",
    excerpt: "A comprehensive review of the most significant sports law cases in Ethiopia over the past year, featuring key victories and emerging legal trends.",
    date: "Dec 2024",
    category: "Annual Review",
    content: "2024 was a landmark year for Ethiopian sports law. From the full CAS clearance of Olympian Diribe Welteji to the significant sanction reduction for Gaddisa Tajebe, Ethiopian athletes achieved remarkable legal victories. This review examines the key cases, their implications for Ethiopian sports law, and the emerging trends that will shape athlete representation in 2025.",
    author: "YMA Law Office",
    readTime: "6 min read",
  },
  {
    id: "nl-3",
    title: "Understanding Your Rights: A Guide for Ethiopian Athletes",
    excerpt: "Essential legal knowledge every Ethiopian athlete should have, from anti-doping procedures to contract rights and dispute resolution mechanisms.",
    date: "Nov 2024",
    category: "Athlete Guide",
    content: "Every athlete deserves to understand their legal rights. This guide covers the fundamental legal protections available to Ethiopian athletes, including anti-doping procedures, contract negotiation basics, the appeals process, and how to access legal representation. Knowledge is power — and knowing your rights is the first step to protecting your career.",
    author: "Yigermal Melkam",
    readTime: "5 min read",
  },
  {
    id: "nl-4",
    title: "The Path to CAS: A Step-by-Step Guide for Ethiopian Athletes",
    excerpt: "Everything you need to know about bringing a case to the Court of Arbitration for Sport, from filing requirements to hearing procedures.",
    date: "Oct 2024",
    category: "Procedural Guide",
    content: "The Court of Arbitration for Sport (CAS) is the highest sporting tribunal in the world, and understanding its procedures is essential for any athlete facing a serious legal challenge. This guide walks through the CAS process step by step, from filing an appeal to the final hearing, with specific considerations for Ethiopian athletes navigating international proceedings.",
    author: "YMA Law Office",
    readTime: "7 min read",
  },
];

export const NEWSLETTER_ARCHIVE = [
  { id: "arch-1", title: "September 2024 — Athlete Rights Update", date: "Sep 2024", summary: "Quarterly update on athlete rights developments and firm news." },
  { id: "arch-2", title: "August 2024 — Anti-Doping Compliance Alert", date: "Aug 2024", summary: "Important compliance update for Ethiopian athletes competing internationally." },
  { id: "arch-3", title: "July 2024 — Mid-Year Legal Review", date: "Jul 2024", summary: "Mid-year review of sports law developments and CAS jurisprudence." },
];